const SCHEMA_VERSION=8,STATE_KEY="luna-state-v8";
const DEFAULT_GROUPS={"\u751f\u6d3b\u7ef4\u6301":["\u4f4f\u623f","\u6c34\u5355","\u533b\u7597","\u8bdd\u8d39","\u65e5\u7528\u54c1","\u51fa\u884c","qqmm"],"\u5473\u89c9\u4f53\u9a8c":["\u98df\u6750","\u96f6\u98df","\u5916\u5356","\u5916\u98df","\u5976\u8336","\u5496\u5561"],"\u7cbe\u795e\u6109\u60a6":["\u4f1a\u5458\u5145\u503c","\u6e38\u620f\u5145\u503c","\u624b\u8d26"],"\u5ba1\u7f8e\u5b9e\u73b0":["\u8863\u670d","\u914d\u9970","\u62a4\u7406","\u5bb6\u5c45\u597d\u7269"],"\u6210\u957f\u6295\u8d44":["\u81ea\u6211\u6295\u8d44","\u7406\u8d22\u8d44\u4ea7"],"\u5173\u7cfb\u4e0e\u610f\u5916":["\u4eba\u60c5\u5f80\u6765\u53ca\u7a81\u53d1\u652f\u51fa"]};
const $=id=>document.getElementById(id),money=n=>"\u00a5"+Number(n||0).toFixed(2);
function safeJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}}
function localDate(value=new Date()){const d=value instanceof Date?value:new Date(value);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
const today=()=>localDate();
function makeId(prefix="item"){return prefix+"-"+(globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2))}
function toCents(value){return Math.round((Number(value)||0)*100)}
function recordValue(record){return Number.isInteger(record?.amountCents)?record.amountCents/100:Number(record?.amount||0)}
function migrateRecord(record){const {amount,...rest}=record||{},stamp=new Date().toISOString(),result={...rest,id:rest.id||makeId("record"),amountCents:Number.isInteger(rest.amountCents)?rest.amountCents:toCents(amount),createdAt:rest.createdAt||stamp,updatedAt:rest.updatedAt||rest.createdAt||stamp};Object.defineProperty(result,"amount",{configurable:true,get(){return (result.amountCents/100).toFixed(2)}});return result}
function migrateTask(task){return {...task,id:task?.id||makeId("task"),createdAt:task?.createdAt||new Date().toISOString()}}
function migrateHealth(item){return {...item,id:item?.id||makeId("health"),createdAt:item?.createdAt||new Date().toISOString()}}
const storedState=safeJSON(STATE_KEY,null)||safeJSON("luna-state-v7",null),storedGroups=storedState?.groups||safeJSON("luna-groups",null)||DEFAULT_GROUPS;
const groups=JSON.parse(JSON.stringify(storedGroups));
let records=(Array.isArray(storedState?.records)?storedState.records:safeJSON("luna-records",[])).map(migrateRecord),health=(Array.isArray(storedState?.health)?storedState.health:safeJSON("luna-health",[])).map(migrateHealth),tasks=(Array.isArray(storedState?.tasks)?storedState.tasks:safeJSON("luna-tasks",[])).map(migrateTask),taskFilter="all",baseIncome=Number.isInteger(storedState?.settings?.baseIncomeCents)?storedState.settings.baseIncomeCents/100:Number(localStorage.getItem("luna-base-income")||0),netWorth=Number.isInteger(storedState?.assets?.currentCents)?storedState.assets.currentCents/100:Number(localStorage.getItem("luna-net-worth")||0),assetSnapshots=(Array.isArray(storedState?.assets?.snapshots)?storedState.assets.snapshots:safeJSON("luna-asset-snapshots",[])).filter(x=>x&&x.date&&Number.isInteger(x.valueCents)),meta={lastBackupAt:storedState?.meta?.lastBackupAt||null,lastSavedAt:storedState?.meta?.lastSavedAt||null};
localStorage.removeItem("luna-papers");
function stateSnapshot(){return {schemaVersion:SCHEMA_VERSION,records,groups,health,tasks,settings:{baseIncomeCents:toCents(baseIncome)},assets:{currentCents:toCents(netWorth),snapshots:assetSnapshots},meta:{...meta,lastSavedAt:new Date().toISOString()}}}
function save(){try{records=records.map(migrateRecord);health=health.map(migrateHealth);tasks=tasks.map(migrateTask);const state=stateSnapshot();meta=state.meta;localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.setItem("luna-records",JSON.stringify(records));localStorage.setItem("luna-groups",JSON.stringify(groups));localStorage.setItem("luna-health",JSON.stringify(health));localStorage.setItem("luna-tasks",JSON.stringify(tasks));localStorage.setItem("luna-base-income",String(baseIncome));localStorage.setItem("luna-net-worth",String(netWorth));localStorage.setItem("luna-asset-snapshots",JSON.stringify(assetSnapshots));updateStorageStatus()}catch(error){console.error("LUNA save failed",error);alert("本地保存失败，请立即导出备份并检查浏览器存储空间。")}}
function monthDays(){const n=new Date();return new Date(n.getFullYear(),n.getMonth()+1,0).getDate()}
function monthBaseIncome(){return baseIncome*monthDays()}
function fill(){const inc=document.querySelector("[name=type]:checked")?.value==="income",a=inc?["\u5de5\u8d44","\u5956\u91d1","\u8d48\u6d4e"]:Object.entries(groups).flatMap(([g,x])=>x.map(v=>g+" \u00b7 "+v));$("category").innerHTML=a.map(v=>"<option>"+v+"</option>").join("")}
function renderCalendar(){const root=$("calendar"),now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),w=["\u65e5","\u4e00","\u4e8c","\u4e09","\u56db","\u4e94","\u516d"];let h='<div class="calendar-head"><b>'+y+' \u5e74 '+(m+1)+' \u6708</b></div><div class="calendar-week">'+w.map(v=>'<span>'+v+'</span>').join('')+'</div><div class="calendar-grid">';for(let i=0;i<first;i++)h+='<span class="calendar-cell blank"></span>';for(let d=1;d<=days;d++){const date=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),rs=records.filter(r=>r.date===date),inc=rs.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0),exp=rs.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0),bal=inc-exp,fill=inc?Math.max(0,Math.min(1,bal/inc)):0,cls=bal<0?'negative':rs.length?'has-record':'';h+='<button class="calendar-cell '+cls+'" style="--fill:'+fill+'" data-date="'+date+'"><span>'+d+'</span>'+(rs.length?'<small>+'+money(inc)+'<br>-'+money(exp)+'</small>':'')+'</button>'}root.innerHTML=h+'</div>';root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{document.querySelector('[name=date]').value=b.dataset.date;$("recordDialog").showModal()})}
function render(){const m=records.filter(r=>r.date.startsWith(today().slice(0,7))),i=m.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0),o=m.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0);$("income").textContent=money(i);$("expense").textContent=money(o);$("balance").textContent=money(i-o);$("records").innerHTML=m.map(r=>'<article class="record"><div><b>'+r.category+'</b><br><small>'+r.date+(r.note?' · '+r.note:'')+'</small></div><strong>'+(r.type==='income'?'+':'-')+money(r.amount)+'</strong></article>').join('')||'<div class="empty">\u672c\u6708\u8fd8\u6ca1\u6709\u8bb0\u5f55</div>';renderCalendar()}
function showCategoryManager(){$("categoryList").innerHTML=Object.entries(groups).map(([g,a])=>'<details class="category-card"><summary>'+g+'<span class="category-meta">\u5305\u542b '+a.length+' \u9879</span></summary><div class="subcategory-list">'+a.map(x=>'<div class="subcategory-row">'+x+'</div>').join('')+'</div></details>').join('');$("categoryDialog").showModal()}
function healthForm(){return '<form id="healthForm" class="module-form"><h3>\u65b0\u589e\u5065\u5eb7\u8bb0\u5f55</h3><div class="form-grid"><label>\u4f53\u91cd\uff08kg\uff09<input name="weight" type="number" step="0.1" min="0" required></label><label>\u6709\u6c27\u7c7b\u578b<input name="aerobicType" placeholder="\u8dd1\u6b65 / \u9a91\u884c"></label><label>\u6709\u6c27\u5206\u949f<input name="aerobic" type="number" min="0" value="0"></label><label>\u65e0\u6c27\u7c7b\u578b<input name="anaerobicType" placeholder="\u6df1\u8e72 / \u529b\u91cf"></label><label>\u65e0\u6c27\u5206\u949f<input name="anaerobic" type="number" min="0" value="0"></label></div><button class="primary" type="submit">+ \u8bb0\u5f55\u672c\u5468</button></form>'}
function renderHealth(){const last=health.slice(-7),weights=last.map(x=>Number(x.weight)),current=weights.at(-1)||0,prev=weights.length>1?weights.at(-2):current,delta=current-prev,total=last.reduce((s,x)=>s+Number(x.aerobic||0)+Number(x.anaerobic||0),0),max=Math.max(...weights,1);$("moduleItems").innerHTML=healthForm()+'<div class="metric-row"><div class="metric"><small>\u5f53\u524d\u4f53\u91cd</small><b>'+(current?current.toFixed(1)+' kg':'—')+'</b></div><div class="metric"><small>\u5468\u53d8\u5316</small><b>'+((delta>0?'+':'')+delta.toFixed(1))+' kg</b></div><div class="metric"><small>\u8fd0\u52a8\u603b\u65f6\u957f</small><b>'+total+' min</b></div></div><section class="module-card"><div><b>\u6700\u8fd17\u6b21\u4f53\u91cd\u8d8b\u52bf</b><div class="trend">'+(last.length?last.map(x=>'<span class="trend-bar" style="height:'+Math.max(8,Number(x.weight)/max*88)+'px" title="'+x.date+' '+x.weight+'kg"></span>').join(''):'<div class="empty">\u8fd8\u6ca1\u6709\u8db3\u591f\u7684\u8bb0\u5f55</div>')+'</div></div></section><section class="module-card"><b>\u672c\u5468\u603b\u7ed3</b><p>\u6709\u6c27 '+last.reduce((s,x)=>s+Number(x.aerobic||0),0)+' min · \u65e0\u6c27 '+last.reduce((s,x)=>s+Number(x.anaerobic||0),0)+' min</p></section><div class="module-list">'+(last.slice().reverse().map(x=>'<article class="module-card"><div><b>'+x.weight+' kg</b><small>'+x.date+' · '+(x.aerobicType||'\u6709\u6c27')+' '+(x.aerobic||0)+'min · '+(x.anaerobicType||'\u65e0\u6c27')+' '+(x.anaerobic||0)+'min</small></div></article>').join('')||'<div class="empty">\u4ece\u65b0\u589e\u4e00\u6b21\u8eab\u4f53\u8bb0\u5f55\u5f00\u59cb</div>')+'</div>';$('healthForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);health.push(migrateHealth({date:today(),weight:Number(d.get('weight')).toFixed(1),aerobicType:d.get('aerobicType'),aerobic:Number(d.get('aerobic')||0),anaerobicType:d.get('anaerobicType'),anaerobic:Number(d.get('anaerobic')||0)}));save();renderHealth()}}
function renderTasks(){const list=tasks.filter(t=>taskFilter==='all'||t.kind===taskFilter),done=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(done/tasks.length*100):0;$("moduleItems").innerHTML='<div class="filter-row">'+['all','day','week'].map(k=>'<button class="'+(taskFilter===k?'active':'')+'" data-filter="'+k+'">'+(k==='all'?'全部':k==='day'?'日任务':'周任务')+'</button>').join('')+'</div><div class="progress-wrap"><div class="progress-label"><span>本周完成率</span><b>'+rate+'%</b></div><div class="progress"><span style="width:'+rate+'%"></span></div></div><form id="taskForm" class="inline-form"><input name="title" placeholder="添加一个任务" required><select name="kind"><option value="day">日任务</option><option value="week">周任务</option></select><button class="primary">添加</button></form><div class="module-list">'+(list.map(t=>'<article class="module-card '+(t.done?'done':'')+'"><button class="check" data-task="'+t.id+'">'+(t.done?'☑':'□')+'</button><div><b>'+t.title+'</b><small>'+(t.kind==='day'?'日任务':'周任务')+'</small></div><button class="card-delete" data-task-delete="'+t.id+'">×</button></article>').join('')||'<div class="empty">还没有任务，先安排一个小目标吧</div>')+'</div>';document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.filter;renderTasks()});$('taskForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);tasks.push({id:Date.now(),title:d.get('title'),kind:d.get('kind'),done:false});save();renderTasks()};document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const t=tasks.find(x=>x.id==b.dataset.task);if(t)t.done=!t.done;save();renderTasks()});document.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=()=>{tasks=tasks.filter(x=>x.id!=b.dataset.taskDelete);save();renderTasks()})}
function renderDashboard(){const now=new Date(),weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));const iso=weekStart.toISOString().slice(0,10),month=records.filter(r=>r.date.startsWith(today().slice(0,7))),balance=month.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0)-month.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0),recentHealth=health.slice(-1)[0],weekRecords=records.filter(r=>r.date>=iso),weekSpend=weekRecords.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0),move=health.filter(x=>x.date>=iso).reduce((s,x)=>s+Number(x.aerobic||0)+Number(x.anaerobic||0),0),done=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(done/tasks.length*100):0;$('todayLabel').textContent=(now.getMonth()+1)+'/'+now.getDate();$('dashBalance').textContent=money(balance);$('dashWeight').textContent=recentHealth?recentHealth.weight+' kg':'—';$('dashProgress').textContent=rate+'%';$('reviewSpend').textContent=money(weekSpend);$('reviewMove').textContent=move+' min';$('reviewStudy').textContent=rate+'%'}
function showModule(n){document.querySelectorAll('.module').forEach(b=>b.classList.toggle('active',b.dataset.module===n));$('detailHeading').textContent=n==='finance'?'\u8d44\u6e90':n==='health'?'\u8eab\u4f53':'\u6210\u957f';const f=n==='finance';document.querySelectorAll('.summary,nav,.view').forEach(x=>x.classList.toggle('hidden',!f));$('personalModules').classList.toggle('hidden',f);if(f)render();else{$('moduleTitle').textContent=$('detailHeading').textContent;n==='health'?renderHealth():renderTasks()}}
function enter(n){document.querySelectorAll('.home-card').forEach(b=>b.classList.remove('home-card-leave'));const home=$('homeView'),detail=$('detailView');home.classList.add('hidden');detail.classList.remove('hidden');home.hidden=true;detail.hidden=false;home.style.display='none';window.scrollTo({top:0,behavior:'smooth'});showModule(n)}
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{b.classList.add('home-card-leave');setTimeout(()=>enter(b.dataset.home),260)});$('backHome').onclick=()=>{document.querySelectorAll('.home-card').forEach(b=>b.classList.remove('home-card-leave'));$('detailView').classList.add('hidden');$('homeView').classList.remove('hidden');renderDashboard()};document.querySelectorAll('.module').forEach(b=>b.onclick=()=>showModule(b.dataset.module));$('manageCategories').onclick=showCategoryManager;$('addTop').onclick=()=>{$('[name=date]').value=today();$('recordDialog').showModal()};$('cancel').onclick=()=>$('recordDialog').close();document.querySelectorAll('[name=type]').forEach(x=>x.onchange=fill);$('recordForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);records.push({type:d.get('type'),amount:Number(d.get('amount')).toFixed(2),category:d.get('category'),date:d.get('date')||today(),note:d.get('note')||''});save();render();renderDashboard();e.currentTarget.reset();fill();$('recordDialog').close()};$('dataTools').onclick=()=>{const d={version:5,records,groups,health,tasks,exportedAt:new Date().toISOString()},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='luna-backup.json';a.click()};fill();render();renderDashboard();
function switchToHome(){const home=document.getElementById('homeView'),detail=document.getElementById('detailView');home.hidden=false;detail.hidden=true;home.classList.remove('hidden');detail.classList.add('hidden');home.style.display='';detail.style.display='none';window.scrollTo(0,0);renderDashboard()}
document.addEventListener('click',e=>{const homeButton=e.target.closest('[data-home]');if(homeButton){e.preventDefault();e.stopImmediatePropagation();enter(homeButton.dataset.home)}},{capture:true});
document.addEventListener('click',e=>{if(e.target.closest('#backHome')){e.preventDefault();e.stopImmediatePropagation();switchToHome()}},{capture:true});
document.addEventListener('click',e=>{if(e.target.closest('#addTop')){e.preventDefault();e.stopImmediatePropagation();const date=document.querySelector('[name=date]');if(date)date.value=today();document.getElementById('recordDialog')?.showModal()}},{capture:true});
document.addEventListener('submit',e=>{if(e.target.id==='taskForm'){e.preventDefault();e.stopImmediatePropagation();const d=new FormData(e.target),title=String(d.get('title')||'').trim();if(!title)return;tasks.push({id:Date.now(),title,kind:d.get('kind')||'day',done:false});save();renderTasks()}},{capture:true});
const addButton=document.getElementById('addTop');if(addButton)addButton.onclick=()=>{const date=document.querySelector('#recordDialog [name=date]');if(date)date.value=today();document.getElementById('recordDialog')?.showModal()};
function openRecordDialog(){const dialog=document.getElementById('recordDialog'),date=dialog?.querySelector('[name=date]');if(date)date.value=today();if(dialog&&!dialog.open){if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}}
if(addButton){addButton.onclick=openRecordDialog;addButton.addEventListener('touchend',e=>{e.preventDefault();openRecordDialog()},{passive:false});addButton.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRecordDialog()}})}

// 每日基础收入：以当月天数自动计入统计与日历，不写入手动明细。
function renderCalendar(){const root=$("calendar"),now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),w=["日","一","二","三","四","五","六"];let h='<div class="calendar-head"><b>'+y+' 年 '+(m+1)+' 月</b></div><div class="calendar-week">'+w.map(v=>'<span>'+v+'</span>').join('')+'</div><div class="calendar-grid">';for(let i=0;i<first;i++)h+='<span class="calendar-cell blank"></span>';for(let d=1;d<=days;d++){const date=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),rs=records.filter(r=>r.date===date),inc=baseIncome+rs.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0),exp=rs.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0),bal=inc-exp,fill=inc?Math.max(0,Math.min(1,bal/inc)):0,cls=bal<0?'negative':(rs.length||baseIncome)?'has-record':'';h+='<button class="calendar-cell '+cls+'" style="--fill:'+fill+'" data-date="'+date+'"><span>'+d+'</span>'+((rs.length||baseIncome)?'<small>+'+money(inc)+'<br>-'+money(exp)+'</small>':'')+'</button>'}root.innerHTML=h+'</div>';root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{document.querySelector('[name=date]').value=b.dataset.date;$("recordDialog").showModal()})}
function render(){const m=records.filter(r=>r.date.startsWith(today().slice(0,7))),i=monthBaseIncome()+m.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0),o=m.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0);$("income").textContent=money(i);$("expense").textContent=money(o);$("balance").textContent=money(i-o);$("records").innerHTML=m.map(r=>'<article class="record"><div><b>'+r.category+'</b><br><small>'+r.date+(r.note?' · '+r.note:'')+'</small></div><strong>'+(r.type==='income'?'+':'-')+money(r.amount)+'</strong></article>').join('')||'<div class="empty">本月还没有手动记录</div>';renderCalendar()}
function setupBaseIncome(){const header=document.querySelector('.header-actions');if(!header||document.getElementById('baseIncomeBtn'))return;const btn=document.createElement('button');btn.id='baseIncomeBtn';btn.className='ghost';btn.textContent='每日收入';header.prepend(btn);const dialog=document.createElement('dialog');dialog.id='baseIncomeDialog';dialog.innerHTML='<form method="dialog" id="baseIncomeForm"><h2>每日基础收入</h2><p class="dialog-hint">设置后，本月每一天都会自动计入这笔基础收入。</p><label>每日金额<input name="baseIncome" type="number" min="0" step="0.01" inputmode="decimal" placeholder="例如 100.00"></label><div class="actions"><button type="button" id="baseIncomeCancel" class="ghost">取消</button><button class="primary">保存</button></div></form>';document.body.append(dialog);btn.onclick=()=>{dialog.querySelector('[name=baseIncome]').value=baseIncome?baseIncome.toFixed(2):'';dialog.showModal()};dialog.querySelector('#baseIncomeCancel').onclick=()=>dialog.close();dialog.querySelector('#baseIncomeForm').onsubmit=e=>{e.preventDefault();baseIncome=Math.max(0,Number(new FormData(e.currentTarget).get('baseIncome')||0));save();dialog.close();render();renderDashboard()}}
setupBaseIncome();render();renderDashboard();
const originalDashboard=renderDashboard;renderDashboard=function(){originalDashboard();const m=records.filter(r=>r.date.startsWith(today().slice(0,7))),manual=m.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0)-m.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0);if($('dashBalance'))$('dashBalance').textContent=money(manual+monthBaseIncome())};
renderDashboard();
const exportButton=$('dataTools');if(exportButton)exportButton.onclick=()=>{meta.lastBackupAt=new Date().toISOString();save();const d={...stateSnapshot(),version:SCHEMA_VERSION,exportedAt:meta.lastBackupAt},a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.href=url;a.download='luna-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);updateStorageStatus()};
function applyImportedData(data){const incomingRecords=Array.isArray(data.records)?data.records:null;if(!incomingRecords)throw new Error('records missing');records=incomingRecords.filter(r=>r&&r.date&&r.type&&(Number.isInteger(r.amountCents)||Number.isFinite(Number(r.amount)))).map(migrateRecord);health=(Array.isArray(data.health)?data.health:[]).map(migrateHealth);tasks=(Array.isArray(data.tasks)?data.tasks:[]).map(migrateTask);if(data.groups&&typeof data.groups==='object'){Object.keys(groups).forEach(k=>delete groups[k]);Object.entries(data.groups).forEach(([k,v])=>{if(Array.isArray(v))groups[k]=v.map(String)})}baseIncome=Math.max(0,Number.isInteger(data.settings?.baseIncomeCents)?data.settings.baseIncomeCents/100:Number(data.baseIncome||0));netWorth=Number.isInteger(data.assets?.currentCents)?data.assets.currentCents/100:Number(data.netWorth||0);assetSnapshots=(Array.isArray(data.assets?.snapshots)?data.assets.snapshots:Array.isArray(data.assetSnapshots)?data.assetSnapshots:[]).filter(x=>x&&x.date&&Number.isInteger(x.valueCents));meta={lastBackupAt:data.meta?.lastBackupAt||data.exportedAt||null,lastSavedAt:null}}
function setupBackupImport(){const header=document.querySelector('.header-actions');if(!header||document.getElementById('importBackupBtn'))return;const btn=document.createElement('button');btn.id='importBackupBtn';btn.className='ghost';btn.textContent='导入备份';const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.id='backupFileInput';document.body.append(input);header.insertBefore(btn,header.firstChild);btn.onclick=()=>input.click();input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!confirm('导入备份会覆盖当前本地数据，确定继续吗？')){input.value='';return}localStorage.setItem('luna-recovery-before-import',JSON.stringify(stateSnapshot()));applyImportedData(data);save();fill();render();renderDashboard();setupRecoveryButton();alert('备份已导入，导入前的数据也已保留在本机')}catch(err){console.error(err);alert('备份文件格式不正确，当前数据没有被覆盖')}input.value=''}}
setupBackupImport();

function showCategoryManager(){const root=$("categoryList");root.innerHTML=Object.entries(groups).map(([g,a])=>'<details class="category-card"><summary>'+g+'<span class="category-meta">包含 '+a.length+' 项</span></summary><div class="subcategory-list">'+a.map((x,i)=>'<div class="subcategory-row"><span>'+x+'</span><button type="button" class="sub-edit" data-group="'+encodeURIComponent(g)+'" data-index="'+i+'">编辑</button></div>').join('')+'</div></details>').join('');$("categoryDialog").showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('.sub-edit');if(!b)return;e.preventDefault();const g=decodeURIComponent(b.dataset.group),i=Number(b.dataset.index),old=groups[g]?.[i],next=prompt('编辑子类别名称',old||'');if(next&&next.trim()&&groups[g]){groups[g][i]=next.trim();save();showCategoryManager();fill();render()}},{capture:true});
function showCategoryManager(){const root=$("categoryList");root.innerHTML=Object.entries(groups).map(([g,a])=>'<details class="category-card"><summary>'+g+'<span class="category-meta">包含 '+a.length+' 项</span></summary><div class="subcategory-list">'+a.map((x,i)=>'<div class="subcategory-row"><span>'+x+'</span><span class="subcategory-actions"><button type="button" class="sub-edit" data-group="'+encodeURIComponent(g)+'" data-index="'+i+'">编辑</button><button type="button" class="sub-delete" data-group="'+encodeURIComponent(g)+'" data-index="'+i+'">删除</button></span></div>').join('')+'<button type="button" class="sub-add" data-group="'+encodeURIComponent(g)+'">＋新增子类别</button></div></details>').join('');$("categoryDialog").showModal()}
document.addEventListener('click',e=>{const add=e.target.closest('.sub-add');if(add){e.preventDefault();const g=decodeURIComponent(add.dataset.group),next=prompt('新增子类别名称','');if(next&&next.trim()&&groups[g]){groups[g].push(next.trim());save();showCategoryManager();fill()};return}const del=e.target.closest('.sub-delete');if(del){e.preventDefault();const g=decodeURIComponent(del.dataset.group),i=Number(del.dataset.index),name=groups[g]?.[i];if(name&&confirm('确定删除子类别“'+name+'”吗？')){groups[g].splice(i,1);save();showCategoryManager();fill();render()}}},{capture:true});

let storagePersistent=false;
function updateStorageStatus(){const header=document.querySelector('#detailView header');if(!header)return;let status=$('storageStatus');if(!status){status=document.createElement('small');status.id='storageStatus';status.className='storage-status';header.append(status)}const backup=meta.lastBackupAt?new Date(meta.lastBackupAt).toLocaleDateString('zh-CN'):'尚未备份';status.textContent='已本地保存 · '+(storagePersistent?'持久存储 · ':'')+'最近备份 '+backup}
async function requestPersistentStorage(){if(!navigator.storage)return;try{storagePersistent=await navigator.storage.persisted();if(!storagePersistent&&navigator.storage.persist)storagePersistent=await navigator.storage.persist();updateStorageStatus()}catch{updateStorageStatus()}}
function setupRecoveryButton(){const header=document.querySelector('.header-actions'),raw=localStorage.getItem('luna-recovery-before-import');if(!header||!raw||$('restoreImportBtn'))return;const btn=document.createElement('button');btn.id='restoreImportBtn';btn.className='ghost subtle';btn.textContent='恢复导入前';btn.onclick=()=>{if(!confirm('恢复到上次导入之前的数据吗？'))return;try{applyImportedData(JSON.parse(localStorage.getItem('luna-recovery-before-import')));save();fill();render();renderDashboardStable();alert('已恢复导入前的数据')}catch{alert('恢复副本不可用')}};header.append(btn)}
function renderDashboardStable(){const now=new Date(),weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));const iso=localDate(weekStart),month=records.filter(r=>r.date.startsWith(today().slice(0,7))),balance=monthBaseIncome()+month.filter(r=>r.type==='income').reduce((s,r)=>s+recordValue(r),0)-month.filter(r=>r.type==='expense').reduce((s,r)=>s+recordValue(r),0),recentHealth=health.slice(-1)[0],weekRecords=records.filter(r=>r.date>=iso),weekSpend=weekRecords.filter(r=>r.type==='expense').reduce((s,r)=>s+recordValue(r),0),move=health.filter(x=>x.date>=iso).reduce((s,x)=>s+Number(x.aerobic||0)+Number(x.anaerobic||0),0),done=tasks.filter(t=>t.done).length,rate=tasks.length?Math.round(done/tasks.length*100):0;$('todayLabel').textContent=(now.getMonth()+1)+'/'+now.getDate();$('dashBalance').textContent=money(balance);$('dashWeight').textContent=recentHealth?recentHealth.weight+' kg':'—';$('dashProgress').textContent=rate+'%';$('reviewSpend').textContent=money(weekSpend);$('reviewMove').textContent=move+' min';$('reviewStudy').textContent=rate+'%'}
renderDashboard=renderDashboardStable;
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function renderStable(){const month=records.filter(r=>r.date.startsWith(today().slice(0,7))),income=monthBaseIncome()+month.filter(r=>r.type==='income').reduce((sum,r)=>sum+recordValue(r),0),expense=month.filter(r=>r.type==='expense').reduce((sum,r)=>sum+recordValue(r),0);$('income').textContent=money(income);$('expense').textContent=money(expense);$('balance').textContent=money(income-expense);$('records').innerHTML=month.map(r=>'<article class="record"><div class="record-main"><b>'+escapeHTML(r.category)+'</b><br><small>'+escapeHTML(r.date)+(r.note?' · '+escapeHTML(r.note):'')+'</small></div><div class="record-side"><strong>'+(r.type==='income'?'+':'-')+money(recordValue(r))+'</strong><button type="button" class="record-delete" data-record-delete="'+escapeHTML(r.id)+'" aria-label="删除这条记录">删除</button></div></article>').join('')||'<div class="empty">本月还没有手动记录</div>';renderCalendar()}
function ensureDailyNetWorthSnapshot(){const todayKey=today(),todayItem=assetSnapshots.find(x=>x.date===todayKey);if(todayItem)return;const ordered=assetSnapshots.slice().sort((a,b)=>a.date.localeCompare(b.date)),last=ordered.at(-1);if(last&&last.date<todayKey){const cursor=new Date(last.date+'T12:00:00'),end=new Date(todayKey+'T12:00:00');let guard=0;while(cursor<end&&guard<4000){cursor.setDate(cursor.getDate()+1);assetSnapshots.push({date:localDate(cursor),valueCents:toCents(netWorth)});guard++}}else assetSnapshots.push({date:todayKey,valueCents:toCents(netWorth)})}
function assetChart(range){const days=range==='week'?7:range==='year'?365:31,cutoff=new Date();cutoff.setDate(cutoff.getDate()-days+1);const start=localDate(cutoff),items=assetSnapshots.filter(x=>x.date>=start).sort((a,b)=>a.date.localeCompare(b.date));if(!items.length)return '<div class="empty asset-empty">设置净资产后，这里会生成变化轨迹</div>';const values=items.map(x=>x.valueCents/100),min=Math.min(...values),max=Math.max(...values),span=max-min||1,points=items.map((x,i)=>{const px=items.length===1?150:12+i*(276/(items.length-1)),py=88-(x.valueCents/100-min)/span*68;return px.toFixed(1)+','+py.toFixed(1)}).join(' ');return '<svg class="asset-chart" viewBox="0 0 300 100" role="img" aria-label="净资产变化曲线"><defs><linearGradient id="assetFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#9279c4" stop-opacity=".28"/><stop offset="1" stop-color="#9279c4" stop-opacity="0"/></linearGradient></defs><polyline class="asset-line-soft" points="'+points+'"/><polyline class="asset-line" points="'+points+'"/></svg><div class="asset-range-label"><span>'+escapeHTML(items[0].date.slice(5))+'</span><span>'+escapeHTML(items.at(-1).date.slice(5))+'</span></div>'}
function renderStats(){const month=records.filter(r=>r.date.startsWith(today().slice(0,7))),expenseGroups={};month.filter(r=>r.type==='expense').forEach(r=>{const name=String(r.category||'其他').split(' · ')[0];expenseGroups[name]=(expenseGroups[name]||0)+recordValue(r)});const rows=Object.entries(expenseGroups).sort((a,b)=>b[1]-a[1]),max=Math.max(...rows.map(x=>x[1]),1),range=$('assetRange')?.value||'month';$('stats').innerHTML='<section class="asset-panel"><div class="asset-heading"><div><small>当前净资产</small><strong>'+money(netWorth)+'</strong></div><button type="button" id="editNetWorth" class="asset-edit" aria-label="编辑当前净资产">✎</button></div><div class="asset-controls"><span>变化轨迹</span><select id="assetRange" aria-label="净资产统计周期"><option value="week" '+(range==='week'?'selected':'')+'>周</option><option value="month" '+(range==='month'?'selected':'')+'>月</option><option value="year" '+(range==='year'?'selected':'')+'>年</option></select></div>'+assetChart(range)+'</section><section class="expense-summary"><h3>本月支出分布</h3>'+(rows.map(([name,value])=>'<article class="stat"><div><b>'+escapeHTML(name)+'</b><small>'+money(value)+'</small></div><div class="stat-track"><span style="width:'+Math.max(4,value/max*100)+'%"></span></div></article>').join('')||'<div class="empty">本月还没有支出记录</div>')+'</section>';$('assetRange').onchange=e=>renderStats();$('editNetWorth').onclick=()=>openNetWorthDialog()}
function setupNetWorthDialog(){if($('netWorthDialog'))return;const dialog=document.createElement('dialog');dialog.id='netWorthDialog';dialog.innerHTML='<form method="dialog" id="netWorthForm"><h2>更新净资产</h2><p class="dialog-hint">保存后会更新今天的净资产快照。</p><label>当前净资产<input name="netWorth" type="number" step="0.01" inputmode="decimal" required></label><div class="actions"><button type="button" id="netWorthCancel" class="ghost">取消</button><button class="primary">保存</button></div></form>';document.body.append(dialog);$('netWorthCancel').onclick=()=>dialog.close();$('netWorthForm').onsubmit=e=>{e.preventDefault();netWorth=Number(new FormData(e.currentTarget).get('netWorth')||0);const todayItem=assetSnapshots.find(x=>x.date===today());if(todayItem)todayItem.valueCents=toCents(netWorth);else assetSnapshots.push({date:today(),valueCents:toCents(netWorth)});save();dialog.close();renderStats()}}
function openNetWorthDialog(){setupNetWorthDialog();$('netWorthDialog').querySelector('[name=netWorth]').value=netWorth.toFixed(2);$('netWorthDialog').showModal()}
function showModuleStable(name){document.querySelectorAll('.module').forEach(button=>button.classList.toggle('active',button.dataset.module===name));$('detailHeading').textContent=name==='finance'?'资源':name==='health'?'身体':'成长';const finance=name==='finance';document.querySelector('.summary').classList.toggle('hidden',!finance);document.querySelector('nav').classList.toggle('hidden',!finance);$('personalModules').classList.toggle('hidden',finance);if(finance){const active=document.querySelector('.tab.active')?.dataset.view||'records';$('recordsView').classList.toggle('hidden',active!=='records');$('statsView').classList.toggle('hidden',active!=='stats');renderStable();if(active==='stats')renderStats()}else{$('recordsView').classList.add('hidden');$('statsView').classList.add('hidden');$('moduleTitle').textContent=$('detailHeading').textContent;name==='health'?renderHealth():renderTasks()}}
function compactAmount(value){const number=Number(value||0),absolute=Math.abs(number);if(absolute>=10000)return (number/10000).toFixed(absolute>=100000?0:1).replace(/\.0$/,'')+'万';if(absolute>=1000)return (number/1000).toFixed(1).replace(/\.0$/,'')+'k';if(Number.isInteger(number))return String(number);return number.toFixed(1)}
function renderCalendar(){const root=$("calendar"),now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(),week=["日","一","二","三","四","五","六"];let html='<div class="calendar-head"><b>'+year+' 年 '+(month+1)+' 月</b><span class="calendar-phase" aria-hidden="true"></span></div><div class="calendar-week">'+week.map(value=>'<span>'+value+'</span>').join('')+'</div><div class="calendar-grid">';for(let index=0;index<first;index++)html+='<span class="calendar-cell blank"></span>';for(let day=1;day<=days;day++){const date=year+'-'+String(month+1).padStart(2,'0')+'-'+String(day).padStart(2,'0'),daily=records.filter(record=>record.date===date),income=baseIncome+daily.filter(record=>record.type==='income').reduce((sum,record)=>sum+recordValue(record),0),expense=daily.filter(record=>record.type==='expense').reduce((sum,record)=>sum+recordValue(record),0),balance=income-expense,ratio=income?Math.max(0,Math.min(1,balance/income)):0,classes=[balance<0?'negative':'',daily.length?'recorded':'',income?'has-income':'',date===today()?'today':''].filter(Boolean).join(' '),hasAmount=daily.length||baseIncome;html+='<button class="calendar-cell '+classes+'" style="--fill:'+ratio+'" data-date="'+date+'" title="'+date+' · 收入 '+money(income)+' · 支出 '+money(expense)+'"><span class="day-number">'+day+'</span>'+(daily.length?'<i class="calendar-moon" aria-hidden="true"></i>':'')+(hasAmount?'<small><span>+'+compactAmount(income)+'</span><span>−'+compactAmount(expense)+'</span></small>':'')+'</button>'}root.innerHTML=html+'</div>';root.querySelectorAll('[data-date]').forEach(button=>button.onclick=()=>{document.querySelector('[name=date]').value=button.dataset.date;$('recordDialog').showModal()})}
render=renderStable;showModule=showModuleStable;
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item===tab));const stats=tab.dataset.view==='stats';$('recordsView').classList.toggle('hidden',stats);$('statsView').classList.toggle('hidden',!stats);if(stats)renderStats();else renderStable()});
document.addEventListener('click',event=>{const button=event.target.closest('[data-record-delete]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();const record=records.find(item=>item.id===button.dataset.recordDelete);if(!record||!confirm('确定删除这条'+(record.type==='income'?'收入':'支出')+'记录吗？'))return;records=records.filter(item=>item.id!==record.id);save();renderStable();renderDashboardStable();if(!$('statsView').classList.contains('hidden'))renderStats()},{capture:true});
ensureDailyNetWorthSnapshot();setupNetWorthDialog();save();setupRecoveryButton();requestPersistentStorage();renderStable();renderDashboardStable();if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration().then(registration=>registration?.update()).catch(()=>{});
